name: Crear APK Android

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Preparar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Preparar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Instalar dependencias
        run: npm install

      - name: Compilar aplicación
        run: npm run build

      - name: Crear proyecto Android
        run: npx cap add android

      - name: Sincronizar Android
        run: npx cap sync android

      - name: Dar permisos a Gradle
        run: chmod +x android/gradlew

      - name: Crear APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: Servicios-Grua-Android
          path: android/app/build/outputs/apk/debug/app-debug.apk
